#let acronyms = (
  API: "Application Programming Interface",
  CAP: "Cloud Application Programming Model",
  CDL: "CDS Definition Language",
  CDS: "Core Data Services",
  CQL: "Core Query Language",
  CSS: "Cascading Style Sheets",
  CSN: "Core Schema Notation",
  CXL: "Core Expression Language",
  DSR: "Design Science Research",
  HANA: "High-Performance Analytic Appliance",
  HTML: "Hypertext Markup Language",
  IDE: "Integrated Development Environment",
  JSON: "JavaScript Object Notation",
  LS: "Language Server",
  LSP: "Language Server Protocol",
  RPC: "Remote Procedure Call",
  SAP: "Systems, Applications, and Products",
  SDK: "Software Development Kit",
  UI: "User Interface",
  URI: "Uniform Resource Identifier",
  VS: "Visual Studio",
  VSIX: "Visual Studio Extension",
)