#let glossary = (
  // === Abkürzungen ===
  "_Abkürzungen": "",
  API: "Application Programming Interface",
  AST: "Abstract Syntax Tree",
  CAP: "Cloud Application Programming Model",
  CDL: "CDS Definition Language",
  CDS: "Core Data Services",
  CSN: "Core Schema Notation",
  CSS: "Cascading Style Sheets",
  DSR: "Design Science Research",
  HTML: "Hypertext Markup Language",
  IDE: "Integrated Development Environment",
  JSON: "JavaScript Object Notation",
  LSP: "Language Server Protocol",
  SaaS: "Software as a Service",
  SDK: "Software Development Kit",
  UI: "User Interface",
  URI: "Uniform Resource Identifier",
  VSIX: "Visual Studio Extension",

  // === Fachbegriffe ===
  "_Fachbegriffe": "",
  AsyncAPI: "Spezifikation zur Beschreibung ereignisgesteuerter APIs, ähnlich zu OpenAPI für REST-APIs",
  Composition: "Starke Beziehung zwischen zwei Entities in CDS, bei der die abhängige Entity ohne die Haupt-Entity nicht existieren kann",
  "Domain-Driven Design": "Softwareentwicklungsansatz, der die fachliche Domäne und deren Modellierung in den Mittelpunkt stellt",
  "Domänenspezifische Sprache": "Programmier- oder Modellierungssprache, die für einen spezifischen Anwendungsbereich entwickelt wurde",
  "Enterprise-Anwendung": "Geschäftsanwendung für Unternehmen mit hoher Komplexität und Skalierbarkeit",
  Extension: "Erweiterung für VS Code, die zusätzliche Funktionalität bereitstellt",
  "Go-to-Definition": "IDE-Funktion, die es ermöglicht, direkt zur Definition eines Symbols im Quellcode zu springen",
  HANA: "High-Performance Analytic Appliance - In-Memory-Datenbanksystem von SAP",
  JavaScript: "Interpretierte Programmiersprache für clientseitige und serverseitige Webanwendungen, bildet die Grundlage für TypeScript",
  "JSON-RPC": "JSON Remote Procedure Call - Protokoll für entfernte Prozeduraufrufe über JSON",
  "Kognitive Belastung": "Mentale Anstrengung, die beim Verarbeiten von Informationen entsteht, wobei die menschliche Verarbeitungskapazität begrenzt ist",
  "Language Server": "Separater Prozess, der Sprachanalyse übernimmt und intelligente IDE-Funktionen wie Autovervollständigung, Fehleranzeige und Go-to-Definition bereitstellt",
  Marketplace: "Plattform zur Veröffentlichung und Distribution von VS Code Extensions",
  "Mehrschichtige Architektur": "Softwarearchitektur-Muster, bei dem die Anwendung in logische Schichten unterteilt wird",
  npm: "Node Package Manager - Standard-Paketmanager für JavaScript- und TypeScript-Projekte zur Verwaltung von Abhängigkeiten und Build-Skripten",
  Nutzwertanalyse: "Entscheidungsmethode, bei der verschiedene Lösungsalternativen anhand gewichteter Kriterien bewertet und verglichen werden",
  OData: "Open Data Protocol - standardisiertes REST-basiertes Protokoll für den Zugriff auf und die Manipulation von Daten über HTTP",
  OpenAPI: "Standardisierte Spezifikation zur Beschreibung von REST-APIs, ermöglicht maschinell lesbare API-Dokumentation",
  "Outline-Ansicht": "Strukturierte Übersicht aller Symbole und Definitionen innerhalb einer einzelnen Datei in einer IDE",
  Parser: "Programm, das Quellcode analysiert und in eine strukturierte Repräsentation überführt, um die syntaktische Struktur zu verstehen",
  Performance: "Leistungsfähigkeit einer Software hinsichtlich Geschwindigkeit und Reaktionszeit",
  PostgreSQL: "Open-Source relationales Datenbankmanagementsystem mit Unterstützung für SQL und erweiterte Datentypen",
  Prototyp: "Frühe, funktionale Version einer Software, die zentrale Funktionalitäten demonstriert",
  "SAP CAP": "SAP Cloud Application Programming Model - Framework von SAP zur Entwicklung von Enterprise-Anwendungen, das auf dem Prinzip der Separation of Concerns basiert",
  "Separation of Concerns": "Architekturprinzip, bei dem verschiedene Aspekte einer Anwendung (z.B. Datenmodell, Services, UI) in separate Module getrennt werden, um Wartbarkeit und Skalierbarkeit zu verbessern",
  "Serviceorientierte Architektur": "Architekturprinzip, bei dem Funktionalität über klar definierte APIs zugänglich gemacht wird",
  Skalierbarkeit: "Fähigkeit eines Systems, mit wachsenden Anforderungen effizient umzugehen",
  SQLite: "Leichtgewichtige, dateibasierte relationale Datenbank, häufig verwendet für Entwicklung und Tests",
  TypeScript: "Typsichere Programmiersprache, die auf JavaScript aufbaut und statische Typprüfung zur Compile-Zeit bietet",
  "VS Code": "Visual Studio Code - populäre, erweiterbare Code-Editor-Plattform von Microsoft",
)
