#import "../vendor/supercharged-dhbw/lib.typ": *

= Sicherheitsrisiken von MCP <sicherheit>

== Bedrohungsmodell und Angreifertypen

Mit dem #acr("MCP") verschiebt sich das Bedrohungsmodell von #acr("KI")-Anwendungen grundlegend. Fang et al. argumentieren, dass die klassische #acr("LLM")-Sicherheitsforschung von einer dyadischen Beziehung zwischen Nutzer und Modell ausgeht, während das #acr("MCP") Drittanbieter als eigenständige Akteure einführt, die weder vom Nutzer noch vom Modellanbieter kontrolliert werden und eigene ökonomische Anreize verfolgen @fang2025thirdparty. Hou et al. systematisieren die Bedrohungslage in einer Taxonomie mit vier Angreifertypen, nämlich böswilligen Server-Entwicklern, externen Angreifern, böswilligen Nutzern und allgemeinen Sicherheitslücken @hou2025mcp. Die vorliegende Arbeit konzentriert sich auf die ersten beiden Typen, da sie die #acr("MCP")-spezifischen Vektoren begründen.

Die Ziele dieser Angreifer umfassen die Exfiltration sensibler Daten, die Ausführung unautorisierter Aktionen über die Werkzeugzugriffe des Agenten und die Manipulation des Modellverhaltens selbst @hou2025mcp. Begünstigt werden sie durch das in @sicherheitsrelevante-designentscheidungen beschriebene Vertrauensproblem, da Hosts Werkzeuge allein anhand textueller Namen und Beschreibungen auswählen, ohne deren Herkunft kryptografisch verifizieren zu können @hou2025mcp.

== Angriffsvektoren

=== Indirect Prompt Injection

_Prompt Injection_ bezeichnet das Einschleusen von Anweisungen, die die ursprünglichen Instruktionen des Modells überschreiben. Bei der direkten Variante stammen diese vom Nutzer selbst; sicherheitlich relevanter für das #acr("MCP") ist die #acr("IPI"), bei der Angreifer Anweisungen in externen Inhalten platzieren, die ein Werkzeug in den Modellkontext lädt @greshake2023injection. Da #acr("MCP")-Server typischerweise genau solche Inhalte liefern, also Webseiten, Dateien, E-Mails oder Datenbankauszüge, bildet jede Resource und jede Tool-Ausgabe einen möglichen Injektionskanal.

Radosevich und Halloran demonstrieren dies mit einer _Retrieval-Agent Deception_ (RADE) genannten Variante: Ein Angreifer platziert Schadanweisungen in einem öffentlich verfügbaren Dokument, das ein Retrieval-Server automatisch in seinen Index aufnimmt; eine reguläre Suchanfrage des Nutzers genügt anschließend, um die Anweisungen in den Modellkontext zu laden und auszuführen, ohne dass der Angreifer je direkten Zugriff auf das System hatte @radosevich2025audit.

Dem Vektor liegt ein strukturelles Problem zugrunde: Das Sprachmodell verarbeitet System-Prompt, Nutzereingabe und Werkzeugausgabe als einen einzigen Token-Strom und kann zwischen Daten und Anweisungen nicht zuverlässig unterscheiden @greshake2023injection.

=== Tool Poisoning und bösartige Server

Beim _Tool Poisoning_ bettet ein böswilliger Server-Entwickler Anweisungen direkt in die Metadaten eines Werkzeugs ein; es handelt sich damit um eine Form der Prompt Injection. Die präparierte Beschreibung gelangt bei der Registrierung des Servers in den Modellkontext, bleibt für den Nutzer aber praktisch unsichtbar @wang2025mcptox. Wang et al. unterscheiden in ihrer Untersuchung drei Angriffsstrategien.

Beim _Explicit Function Hijacking_ tarnt sich das vergiftete Werkzeug als gewünschte Funktion und ergänzt seine Beschreibung um eine vorgelagerte Anweisung, etwa das Auslesen privater Schlüsseldateien vor der eigentlichen Operation. Beim _Implicit Function Hijacking_ definiert die Beschreibung eine globale Regel, die jeden vergleichbaren Werkzeugaufruf um die Schadanweisung erweitert, sodass das vergiftete Werkzeug selbst nie aufgerufen werden muss. Die dritte Strategie, das _Parameter Tampering_, manipuliert nicht das Verhalten, sondern die Argumente eines anderen, legitimen Werkzeugs, beispielsweise den Empfänger eines Mailaufrufs @wang2025mcptox.

Wang et al. weisen die Wirksamkeit dieser Strategien mit dem Benchmark MCPTox auf 45 realen #acr("MCP")-Servern und 1312 Testfällen nach. Im Mittel führen die untersuchten Agenten die eingeschleusten Anweisungen in 36,5 Prozent der Fälle aus, das anfälligste Modell o1-mini in 72,8 Prozent; das Parameter Tampering erreicht die höchste durchschnittliche Erfolgsrate. Leistungsfähigere Modelle erweisen sich dabei als anfälliger, weil sie Anweisungen zuverlässiger befolgen, und verweigern die Ausführung in weniger als drei Prozent der Fälle @wang2025mcptox. Klassische Berechtigungsmodelle für „neue Tools" greifen nicht, da die schädliche Aktion ein bereits genehmigtes legitimes Werkzeug übernimmt.

Zwei Varianten verschärfen das Problem. Beim _Rug Pull_ verhält sich ein Server zunächst unauffällig und ändert seine Werkzeugdefinitionen erst, nachdem der Nutzer ihn einmalig genehmigt hat @hou2025mcp. Beim _Cross-Server Shadowing_ überschreibt ein bösartiger Server das Verhalten parallel verbundener vertrauenswürdiger Server, indem er in seiner eigenen Werkzeugbeschreibung Hinweise zu deren Aufrufen platziert, etwa zur Umleitung von Zugangsdaten an den Angreifer @hou2025mcp. Fang et al. zeigen ergänzend, dass einfache statische Filter solche bösartigen Dienste nicht zuverlässig erkennen @fang2025thirdparty.

=== Manipulation der Werkzeugauswahl

Der dritte Vektor zielt nicht auf das Verhalten eines Werkzeugs, sondern auf den vorgelagerten Auswahlschritt. Bevor das Modell ein Werkzeug aufruft, ranken Hosts die verfügbaren Funktionen typischerweise zweistufig: Ein Retriever schlägt anhand der Nutzeranfrage Kandidaten vor, das Sprachmodell trifft daraus die endgültige Auswahl. Shi et al. demonstrieren mit _ToolHijacker_, dass ein einzelnes präpariertes Werkzeugdokument beide Stufen gleichzeitig manipulieren kann. Der Angriff arbeitet im No-Box-Setting, also ohne Zugriff auf das Zielsystem, und erreicht in der MetaTool-Auswertung auf GPT-4o eine Erfolgsrate von 96,7 Prozent. Verbreitete präventive und detektive Abwehrmechanismen erkennen die optimierten Eingaben überwiegend nicht @shi2025promptinjection.

Eine ökonomische Variante übertragen Wang et al. mit der _MCP Preference Manipulation Attack_ auf das Ökosystem. Anbieter eines kostenpflichtigen Servers gestalten Tool-Name und Beschreibung so, dass das Modell ihren Server gegenüber funktional gleichwertigen Konkurrenten bevorzugt. Eine genetisch optimierte Variante (GAPMA) erreicht auf Gemini-2.5-flash eine Erfolgsrate von 91,88 Prozent bei einer Falsch-Positiv-Rate nahe null; allein für Web-Search-#acr("MCP")-Server schätzen die Autoren den unfairen Marktvorteil auf rund 248 000 USD pro Jahr. Bestehende Sicherheitsscanner erkennen diese Manipulation praktisch nicht @wang2025mpma.

Beide Angriffe sitzen damit vor jeder Werkzeugausführung. Sie zeigen, dass weder Sandboxing einzelner Server noch eine Beschränkung der Tool-Berechtigungen ausreichen, weil das Modell den Werkzeugaufruf bereits manipuliert auslöst.

=== Tool Chaining und Sandbox Escape

Auch ohne kompromittierte Metadaten lassen sich legitime Werkzeuge zu schädlichen Abläufen kombinieren. Hou et al. beschreiben den _Tool Chaining Abuse_, bei dem ein Modell mehrere einzeln als unkritisch eingestufte Werkzeuge zu einer Hochrisiko-Pipeline verkettet, etwa Verzeichnislisting, das Lesen einer Konfigurationsdatei, eine Datenbankabfrage und eine schreibende Operation in ein öffentlich erreichbares Verzeichnis @hou2025mcp. Fang et al. beobachten dieselbe Dynamik im Drittanbieter-Verbund: Eine in einem schwächer geschützten Dienst eingebrachte Anweisung propagiert über die Werkzeugkette in nachgelagerte Dienste und überschreitet damit Vertrauensgrenzen, die kein einzelner Server kontrollieren kann @fang2025thirdparty.

Die Reichweite solcher Ketten wird durch die fehlende Laufzeitisolation des #acr("MCP") verschärft. Die Spezifikation schreibt keine Sandbox-Mechanismen vor, sodass ein Filesystem-Server ohne Pfadbeschränkung das Schreiben in beliebige Stellen des Heimatverzeichnisses erlaubt. Radosevich und Halloran zeigen entsprechend, dass ein Eintrag in `~/.bashrc` beim nächsten Terminalstart eine Reverse-Shell aktiviert, während ein zusätzlicher öffentlicher Schlüssel in `~/.ssh/authorized_keys` einen sofortigen SSH-Zugriff eröffnet @radosevich2025audit.

Eng verwandt ist der Diebstahl persistent gespeicherter Zugangsdaten. Hou et al. weisen darauf hin, dass viele Hosts API-Schlüssel im Klartext in Konfigurationsdateien wie `claude_desktop_config.json` an vorhersehbaren Pfaden ablegen @hou2025mcp. Radosevich und Halloran demonstrieren die Folge anhand des Everything-Servers: Ein `printEnv`-Werkzeug liest die Umgebungsvariablen mitsamt Tokens aus, die der Agent anschließend über einen Slack-Server in einen vom Angreifer kontrollierten Kanal sendet @radosevich2025audit.

== Gegenmaßnahmen und ihre Grenzen

Narajala und Habler schlagen für den produktiven Einsatz des #acr("MCP") ein mehrschichtiges Sicherheitsframework nach den Prinzipien Defense-in-Depth und Zero Trust vor. Jeder Zugriff wird unabhängig von seiner Herkunft verifiziert, Berechtigungen werden nach dem Least-Privilege-Prinzip möglichst eng und zeitlich begrenzt vergeben @narajala2025enterprise. Die einzelnen Maßnahmen lassen sich den vorangegangenen Vektoren zuordnen.

Gegen Tool Poisoning und Manipulation der Werkzeugauswahl richten sich Kontrollen der Werkzeug-Metadaten. Tool-Beschreibungen sind als potenziell ausführbare Inhalte zu behandeln, also vor der Registrierung zu validieren, auf bekannte Anweisungsmuster zu prüfen und um aktive Inhalte zu bereinigen @narajala2025enterprise. Gegen Rug Pulls hilft die kryptografische Integritätssicherung genehmigter Beschreibungen, da nachträgliche Änderungen so erkennbar werden @narajala2025enterprise. Cross-Server Shadowing und ähnliche Vektoren adressieren signierte Server-Manifeste, verifizierte Herausgeber und eine zentrale Namensraumverwaltung, wie sie Hou et al. für künftige Protokollversionen fordern @hou2025mcp.

Tool Chaining und Sandbox Escape begrenzen Containerisierung mit restriktivem Egress-Filter, eine OAuth-basierte Autorisierung mit eng zugeschnittenen, kurzlebigen Tokens und die Just-in-Time-Freigabe einzelner Werkzeuge erst bei tatsächlichem Bedarf @narajala2025enterprise. File Integrity Monitoring kritischer Pfade wie `~/.bashrc` oder `~/.ssh/authorized_keys` erkennt zudem die in @sicherheit dokumentierten Persistenzangriffe @radosevich2025audit.

Gegen #acr("IPI") existiert dagegen keine ebenso gezielte Abwehr. Die Maßnahmen wirken hier eindämmend statt verhindernd, indem Sandboxing kompromittierte Werkzeuge isoliert und Verhaltensüberwachung anomale Aufrufe und Datenabflüsse zur Laufzeit erkennt @narajala2025enterprise. Eine strukturelle Schutzwirkung bleibt aus, solange Sprachmodelle Daten und Anweisungen im selben Kontext verarbeiten und nicht zuverlässig trennen können @greshake2023injection. Shi et al. zeigen empirisch, dass gängige präventive wie detektive Mechanismen optimierte Angriffe auf die Werkzeugauswahl mehrheitlich nicht erkennen @shi2025promptinjection. Die verfügbaren Maßnahmen reduzieren damit die Angriffsfläche und den möglichen Schaden, beseitigen die Verwundbarkeit aber nicht. Welche Schlussfolgerungen sich daraus für den Einsatz des #acr("MCP") ergeben, fasst das folgende Kapitel zusammen.
